
name: CD

on:
  push:
    branches:
      - main
      - dev
      - homolog

  workflow_dispatch:

jobs:
  DeployToAWS:
    environment:
        name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
        - uses: actions/checkout@v2
        - name: Setup AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-region: ${{ vars.AWS_REGION }}
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
            role-session-name: github-action

        - name: Setting stage and stack name
          run: |
            echo "STAGE=${{ github.ref_name }}" 
            echo "STACK_NAME=SmileActivity2023Stack${{github.ref_name}}" >> $GITHUB_ENV

        - name: Installing Dependencies
          run: |
            npm install -g aws-cdk
            cd iac
            pip install -r requirements.txt

        - name: DeployWithCDK
          run: |
            cd iac
            cdk synth
            cdk deploy "${{env.STACK_NAME}}-certificates-s3" --require-approval never 
            cdk deploy "${{env.STACK_NAME}}" --require-approval never 

          env:
              AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
              AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
              USER_POOL_ARN: ${{ secrets.USER_POOL_ARN }}
              USER_POOL_NAME: ${{ secrets.USER_POOL_NAME }}
              USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
              STACK_NAME: ${{ env.STACK_NAME }}
              GITHUB_REF: ${{ github.ref }}
              FROM_EMAIL: ${{ vars.FROM_EMAIL }}
              HIDDEN_COPY: ${{ vars.HIDDEN_COPY }}
              HASH_KEY: ${{ secrets.HASH_KEY }}
