name: Create PR

on:
  push:
    branches:
      - dev
      - homolog

jobs: 
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR list
        run: |
          lenPrs=$(gh pr list -B homolog -H dev --json id,title --jq '. | length')
          echo "lenPrs=$lenPrs" >> $GITHUB_ENV
      - name: Validate already exists open PR
        if: ${{ env.lenPrs }} == 1
        run: exit_with_success
  create-pr-homolog:
    needs: check_pr
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create PR dev into homolog
        env:
          repo: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
            reviewers=$(gh api "repos/$repo/collaborators?permission=admin" --jq '[.[] | .login] | join(",")')
            gh pr create -B homolog -H dev --title "Merge branch dev -> homolog - Criado Automatico" --body "Criado Automaticamente" --reviewer "$reviewers"
        
  create-pr-prod:
    needs: check_pr
    if: github.ref == 'refs/heads/homolog'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create PR homolog into prod  
        env:
          repo: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
            reviewers=$(gh api "repos/$repo/collaborators?permission=admin" --jq '[.[] | .login] | join(",")')
            gh pr create -B prod -H homolog --title "Merge branch homolog -> prod - Criado Automatico" --body "Criado Automaticamente" --reviewer "$reviewers"
