name: Create PR

on:
  push:
    branches:
      - dev
      - homolog

jobs:   
  create-pr-homolog:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Create PR dev into homolog
        env:
          repo: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
            reviewers=$(gh api "repos/$repo/collaborators?permission=admin" --jq '[.[] | .login] | join(",")')
            gh pr create -B homolog -H dev --title "Merge branch dev -> homolog - Criado Automatico" --body "Criado Automaticamente" --reviewer "$reviewers"
        
  create-pr-prod:
    if: github.ref == 'refs/heads/homolog'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create PR homolog into prod  
        env:
          repo: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
            reviewers=$(gh api "repos/$repo/collaborators?permission=admin" --jq '[.[] | .login] | join(",")')
            gh pr create -B homolog -H prod --title "Merge branch homolog -> prod - Criado Automatico" --body "Criado Automaticamente" --reviewer "$reviewers"
