name: Check Approve Owner repository

on:
  pull_request:
    branches:
      - homolog
  pull_request_review:
    types: [submitted]

jobs: 
  valid_owner:
    runs-on: ubuntu-latest
    env:
      author: ${{ github.event.pull_request.user.login }}
      repo: ${{ github.repository }}
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: set inicial status
        if: github.event_name == 'pull_request'
        run: |
          exit 1

      - name: get permission
        if: github.event.review.state == 'approved'
        run: |
          perm=$(gh api "repos/$repo/collaborators/$author/permission" --jq '.permission')
          echo "perm=$perm" >> $GITHUB_ENV
      - name: set pending run
        if: ${{ env.perm != 'admin' &&  github.event_name != 'pull_request' }}
        run: |
          exir 1

